import Link from "next/link";
import type { DuLieuTrangChuTheme } from "@/themes/types";
import { AnhBaiViet, LinkBaiViet } from "@/themes/dung-chung";

export function TrangChuOrganicGreen({ duLieu }: { duLieu: DuLieuTrangChuTheme }) {
  const noiBat=duLieu.danhSachBaiViet[0];
  return <main className="min-h-screen bg-[#fffdf6] text-[#17351f]">
    <section className="mx-auto max-w-7xl px-4 pt-6"><div className="relative min-h-[560px] overflow-hidden rounded-[32px] bg-[#315a2d]">{noiBat?<AnhBaiViet baiViet={noiBat} className="absolute inset-0 h-full w-full object-cover opacity-55"/>:null}<div className="absolute inset-0 bg-gradient-to-r from-green-950/70 via-green-900/30 to-transparent"/><div className="relative flex min-h-[560px] max-w-3xl flex-col justify-center px-7 py-12 text-white md:px-16"><p className="font-bold text-yellow-300">NỘI DUNG BỀN VỮNG · GIÁ TRỊ THỰC</p><h1 className="mt-4 text-5xl font-black leading-tight md:text-7xl">{duLieu.tenWebsite}</h1><p className="mt-5 text-lg leading-8 text-green-50">{duLieu.moTaWebsite}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#noi-dung" className="rounded-full bg-yellow-300 px-7 py-3 font-black text-green-950">Xem nội dung</a><Link href="/dang-bai" className="rounded-full border border-white/60 px-7 py-3 font-black">Đăng bài</Link></div></div></div></section>
    <section className="mx-auto grid max-w-6xl gap-5 px-4 py-12 sm:grid-cols-2 lg:grid-cols-4">{duLieu.danhSachDeMuc.slice(0,4).map((d,i)=><Link key={d.id} href={`/de-muc/${d.duong_dan}`} className="rounded-2xl p-5 text-center transition hover:bg-white hover:shadow-lg"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-green-100 text-3xl">{["🌱","🌾","🍃","🚜"][i]||"🌿"}</span><h3 className="mt-4 font-black">{d.ten_de_muc}</h3><p className="mt-2 text-sm leading-6 text-green-800/70">Khám phá nội dung trong đề mục này.</p></Link>)}</section>
    <section id="noi-dung" className="mx-auto max-w-7xl px-4 py-12"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="font-bold text-green-700">VỀ WEBSITE</p><h2 className="mt-3 text-4xl font-black leading-tight">Chia sẻ kiến thức có giá trị và ứng dụng thực tế.</h2><p className="mt-5 leading-8 text-green-900/70">Nội dung được tổ chức theo đề mục rõ ràng, hỗ trợ người đọc tìm kiếm nhanh và theo dõi các bài viết mới.</p><div className="mt-7 rounded-3xl bg-yellow-300 p-7"><p className="text-sm font-bold">BÀI VIẾT ĐÃ HIỂN THỊ</p><p className="mt-2 text-5xl font-black">{duLieu.danhSachBaiViet.length}+</p></div></div><div className="grid gap-5 sm:grid-cols-2">{duLieu.danhSachBaiViet.slice(0,6).map(b=><LinkBaiViet key={b.id} baiViet={b} className="overflow-hidden rounded-3xl bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><AnhBaiViet baiViet={b} className="h-44 w-full object-cover"/><div className="p-5"><h3 className="text-xl font-black">{b.tieu_de}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-green-900/60">{b.tom_tat}</p></div></LinkBaiViet>)}</div></div></section>
  </main>;
}
