import Link from "next/link";
import type { DuLieuTrangChuTheme } from "@/themes/types";
import { AnhBaiViet, LinkBaiViet } from "@/themes/dung-chung";

export function TrangChuNewsPortal({ duLieu }: { duLieu: DuLieuTrangChuTheme }) {
 const [noiBat,...ds]=duLieu.danhSachBaiViet;
 return <main className="min-h-screen bg-[#f3f4f6] text-slate-900"><section className="mx-auto max-w-7xl px-4 py-7"><div className="grid gap-5 lg:grid-cols-[1fr_330px]"><div className="overflow-hidden rounded-xl bg-white shadow-sm">{noiBat?<LinkBaiViet baiViet={noiBat} className="relative block"><AnhBaiViet baiViet={noiBat} className="h-[380px] w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 to-transparent p-7 text-white"><p className="text-sm font-bold text-red-300">NỔI BẬT</p><h1 className="mt-2 text-3xl font-black">{noiBat.tieu_de}</h1></div></LinkBaiViet>:null}</div><aside className="rounded-xl bg-white p-5 shadow-sm"><h2 className="border-b pb-3 text-xl font-black">Tìm nội dung</h2><input placeholder="Tìm kiếm bài viết..." className="mt-4 h-11 w-full rounded-lg border px-3"/><select className="mt-3 h-11 w-full rounded-lg border px-3"><option>Tất cả đề mục</option>{duLieu.danhSachDeMuc.map(d=><option key={d.id}>{d.ten_de_muc}</option>)}</select><button className="mt-3 h-11 w-full rounded-lg bg-red-600 font-bold text-white">Xem kết quả</button><div className="mt-5 space-y-2">{duLieu.danhSachDeMuc.slice(0,5).map(d=><Link key={d.id} href={`/de-muc/${d.duong_dan}`} className="block rounded-lg bg-slate-50 px-3 py-2 font-semibold hover:bg-red-50 hover:text-red-600">{d.ten_de_muc}</Link>)}</div></aside></div></section>
 <section className="mx-auto max-w-7xl px-4 pb-12"><h2 className="border-b-2 border-red-600 pb-3 text-2xl font-black">Bài viết mới</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{ds.slice(0,8).map(b=><LinkBaiViet key={b.id} baiViet={b} className="overflow-hidden rounded-xl bg-white shadow-sm hover:shadow-lg"><AnhBaiViet baiViet={b} className="h-40 w-full object-cover"/><div className="p-4"><h3 className="line-clamp-2 font-black">{b.tieu_de}</h3><p className="mt-2 text-xs text-slate-500">{b.ngay_dang?new Date(b.ngay_dang).toLocaleDateString("vi-VN"):"Mới cập nhật"}</p></div></LinkBaiViet>)}</div></section>
 <section className="mx-auto grid max-w-7xl gap-5 px-4 pb-14 md:grid-cols-2">{duLieu.danhSachDeMuc.slice(0,2).map((d,i)=><div key={d.id}><div className="flex items-center justify-between border-b-2 border-slate-900 pb-2"><h2 className="text-xl font-black">{d.ten_de_muc}</h2><Link href={`/de-muc/${d.duong_dan}`} className="text-sm font-bold text-red-600">Xem tất cả</Link></div><div className="mt-4 grid grid-cols-2 gap-3">{ds.slice(i*4,i*4+4).map(b=><LinkBaiViet key={b.id} baiViet={b} className="rounded-lg bg-white p-3 shadow-sm"><h3 className="line-clamp-2 font-bold">{b.tieu_de}</h3></LinkBaiViet>)}</div></div>)}</section></main>;
}
