"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
export function CatalogCongKhai({ catalog, cot, thietBi, duongDanChiTiet }:{ catalog:any; cot:any[]; thietBi:any[]; duongDanChiTiet:string }) {
  const [q,setQ]=useState("");
  const ds=useMemo(()=>{const k=q.trim().toLocaleLowerCase("vi");if(!k)return thietBi;return thietBi.filter(t=>{const v=Object.fromEntries((t.catalog_gia_tri||[]).map((x:any)=>[x.cot_id,x.gia_tri||""]));return [t.ten_thiet_bi,...cot.filter(c=>c.cho_tim_kiem).map(c=>v[c.id]||"")].join(" ").toLocaleLowerCase("vi").includes(k)})},[q,cot,thietBi]);
  const hien=cot.filter(c=>c.hien_trong_danh_sach);
  return <section className="mx-auto max-w-7xl px-4 py-8"><h1 className="text-4xl font-black">{catalog.tieu_de}</h1><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm kiếm thiết bị..." className="mt-6 h-12 w-full rounded-xl border bg-white px-4"/><div className="mt-5 overflow-x-auto rounded-2xl bg-white shadow"><table className="min-w-full"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Hình ảnh</th><th className="p-3 text-left">Tên thiết bị</th>{hien.map(c=><th key={c.id} style={{width:c.do_rong}} className="p-3 text-left">{c.ten_cot}</th>)}</tr></thead><tbody>{ds.map(t=>{const v=Object.fromEntries((t.catalog_gia_tri||[]).map((x:any)=>[x.cot_id,x.gia_tri||""]));return <tr key={t.id} className="border-t"><td className="p-3"><Link href={`${duongDanChiTiet}/${t.duong_dan}`}>{t.google_drive_anh_file_id?<img src={`/api/catalog/anh/${t.google_drive_anh_file_id}`} alt="" className="h-20 w-28 rounded-lg object-cover"/>:<div className="h-20 w-28 rounded-lg bg-slate-100"/>}</Link></td><td className="p-3 font-bold"><Link href={`${duongDanChiTiet}/${t.duong_dan}`}>{t.ten_thiet_bi}</Link></td>{hien.map(c=><td key={c.id} className="p-3 align-top">{v[c.id]}</td>)}</tr>})}</tbody></table>{!ds.length?<p className="p-10 text-center">Không tìm thấy thiết bị phù hợp.</p>:null}</div></section>
}
