"use client";
import {useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
type Modal="them"|"sua"|"cot"|"vitri"|null;
export default function Trang(){const{id}=useParams<{id:string}>();const[d,setD]=useState<any>(null);const[dm,setDm]=useState<any[]>([]);const[m,setM]=useState<Modal>(null);const[chone,setChon]=useState<any>(null);const[q,setQ]=useState("");
async function tai(){const r=await fetch(`/api/quan-tri/catalog?id=${id}`,{cache:"no-store"});const k=await r.json();if(!k.thanh_cong)throw new Error(k.loi);setD(k.du_lieu)}
useEffect(()=>{Promise.all([tai(),fetch("/api/quan-tri/de-muc").then(r=>r.json()).then(k=>setDm(k.du_lieu||k.danh_sach||[]))]).catch(e=>alert(e.message))},[id]);
const cot=useMemo(()=>[...(d?.cot||[])].sort((a,b)=>a.thu_tu-b.thu_tu),[d]);const ds=useMemo(()=>{const k=q.trim().toLocaleLowerCase("vi");if(!k)return d?.thiet_bi||[];return(d?.thiet_bi||[]).filter((t:any)=>{const v=Object.fromEntries((t.catalog_gia_tri||[]).map((x:any)=>[x.cot_id,x.gia_tri||""]));return[t.ten_thiet_bi,...cot.filter((c:any)=>c.cho_tim_kiem).map((c:any)=>v[c.id]||"")].join(" ").toLocaleLowerCase("vi").includes(k)})},[d,q,cot]);
async function them(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el),v:any={};cot.forEach((c:any)=>v[c.id]=f.get(`c_${c.id}`)||"");f.set("catalog_id",id);f.set("gia_tri",JSON.stringify(v));const r=await fetch("/api/quan-tri/catalog",{method:"POST",body:f});const k=await r.json();if(!k.thanh_cong)return alert(k.loi);el.reset();setM(null);await tai()}
async function sua(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el),v:any={};cot.forEach((c:any)=>v[c.id]=f.get(`c_${c.id}`)||"");f.set("catalog_id",id);f.set("id",chone.id);f.set("gia_tri",JSON.stringify(v));const r=await fetch("/api/quan-tri/catalog-v2",{method:"PATCH",body:f});const k=await r.json();if(!k.thanh_cong)return alert(k.loi);setM(null);setChon(null);await tai()}
async function xoaTB(t:any){if(!confirm(`Xóa thiết bị ${t.ten_thiet_bi}?`))return;const r=await fetch(`/api/quan-tri/catalog-v2?loai=thiet_bi&id=${t.id}&catalog_id=${id}`,{method:"DELETE"});const k=await r.json();if(!k.thanh_cong)return alert(k.loi);await tai()}
async function luuCot(c:any,patch:any){const r=await fetch("/api/quan-tri/catalog-v2",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({loai:"cot",catalog_id:id,...c,...patch})});const k=await r.json();if(!k.thanh_cong)alert(k.loi);else await tai()}
async function xoaCot(c:any){if(!confirm(`Xóa cột ${c.ten_cot} và toàn bộ dữ liệu trong cột?`))return;const r=await fetch(`/api/quan-tri/catalog-v2?loai=cot&id=${c.id}&catalog_id=${id}`,{method:"DELETE"});const k=await r.json();if(!k.thanh_cong)alert(k.loi);else await tai()}
async function themCot(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);const r=await fetch("/api/quan-tri/catalog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({hanh_dong:"them_cot",catalog_id:id,ten_cot:f.get("ten_cot"),loai_du_lieu:f.get("loai"),do_rong:Number(f.get("rong"))||180,thu_tu:cot.length})});const k=await r.json();if(!k.thanh_cong)alert(k.loi);else{el.reset();await tai()}}
async function luuViTri(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/quan-tri/catalog-v2",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({loai:"catalog",id,catalog_id:id,ten_hien_thi:f.get("ten"),de_muc_id:f.get("dm"),de_muc_con_id:f.get("dmc")||null})});const k=await r.json();if(!k.thanh_cong)alert(k.loi);else{setM(null);await tai()}}
if(!d)return <p className="p-8">Đang tải...</p>;const vals=(t:any)=>Object.fromEntries((t.catalog_gia_tri||[]).map((x:any)=>[x.cot_id,x.gia_tri||""]));const con=dm.find(x=>x.id===d.catalog.de_muc_id)?.de_muc_con||[];
return <main className="min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-[1700px]"><div className="rounded-2xl bg-white p-5 shadow"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-black">Quản lý Catalog</h1><div className="flex flex-wrap gap-2"><button onClick={()=>{setChon(null);setM("them")}} className="rounded-xl bg-blue-600 px-4 py-3 font-bold text-white">+ Thêm thiết bị</button><button onClick={()=>setM("cot")} className="rounded-xl bg-slate-900 px-4 py-3 font-bold text-white">Quản lý cột</button><button onClick={()=>setM("vitri")} className="rounded-xl border px-4 py-3 font-bold">Tên và chỗ hiển thị</button></div></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm kiếm thiết bị..." className="mt-5 h-12 w-full max-w-2xl rounded-xl border px-4"/></div>
<div className="mt-5 overflow-x-auto rounded-2xl bg-white shadow"><table className="min-w-full table-fixed"><thead className="bg-slate-900 text-white"><tr><th className="w-32 p-3 text-left">Hình ảnh</th><th className="w-56 p-3 text-left">Tên thiết bị</th>{cot.filter((c:any)=>c.hien_trong_danh_sach).map((c:any)=><th key={c.id} style={{width:c.do_rong}} className="p-3 text-left">{c.ten_cot}</th>)}<th className="w-40 p-3">Thao tác</th></tr></thead><tbody>{ds.map((t:any)=>{const v=vals(t);return <tr key={t.id} className="border-t"><td className="p-3">{t.google_drive_anh_file_id?<img src={`/api/catalog/anh/${t.google_drive_anh_file_id}`} alt="" className="h-20 w-28 rounded-lg object-cover" onError={e=>{e.currentTarget.style.display="none"}}/>:<div className="h-20 w-28 rounded-lg bg-slate-100"/>}</td><td className="p-3 align-top font-bold">{t.ten_thiet_bi}</td>{cot.filter((c:any)=>c.hien_trong_danh_sach).map((c:any)=><td key={c.id} className="whitespace-pre-wrap p-3 align-top">{v[c.id]}</td>)}<td className="p-3 text-center"><button onClick={()=>{setChon(t);setM("sua")}} className="mr-3 font-bold text-blue-600">Sửa</button><button onClick={()=>xoaTB(t)} className="font-bold text-red-600">Xóa</button></td></tr>})}</tbody></table></div></div>
{m&&<div className="fixed inset-0 z-[300] flex items-center justify-center bg-black/60 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setM(null)}}><div className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{m==="them"?"Thêm thiết bị":m==="sua"?"Sửa thiết bị":m==="cot"?"Quản lý cột":"Tên và chỗ hiển thị"}</h2><button onClick={()=>setM(null)}>Đóng</button></div>
{(m==="them"||m==="sua")&&<form onSubmit={m==="them"?them:sua} className="mt-5 space-y-4"><input name="ten_thiet_bi" required defaultValue={chone?.ten_thiet_bi||""} placeholder="Tên thiết bị" className="h-12 w-full rounded-xl border px-4"/><input name="anh" type="file" accept="image/jpeg,image/png,image/webp" className="w-full rounded-xl border p-3"/>{cot.map((c:any)=>{const v=chone?vals(chone)[c.id]:"";return c.loai_du_lieu==="van_ban_dai"?<textarea key={c.id} name={`c_${c.id}`} defaultValue={v} placeholder={c.ten_cot} className="min-h-28 w-full rounded-xl border p-3"/>:<input key={c.id} name={`c_${c.id}`} defaultValue={v} placeholder={c.ten_cot} className="h-12 w-full rounded-xl border px-4"/>})}<button className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">Lưu thiết bị</button></form>}
{m==="cot"&&<div className="mt-5"><form onSubmit={themCot} className="grid gap-3 md:grid-cols-[1fr_180px_140px_auto]"><input name="ten_cot" required placeholder="Tên cột mới" className="h-11 rounded-xl border px-3"/><select name="loai" className="h-11 rounded-xl border px-3"><option value="van_ban_ngan">Văn bản ngắn</option><option value="van_ban_dai">Văn bản dài</option><option value="so">Số</option><option value="ngay">Ngày</option><option value="lien_ket">Liên kết</option></select><input name="rong" type="number" defaultValue="180" className="h-11 rounded-xl border px-3"/><button className="rounded-xl bg-slate-900 px-4 font-bold text-white">Thêm cột</button></form><div className="mt-5 space-y-3">{cot.map((c:any)=><div key={c.id} className="grid gap-3 rounded-xl bg-slate-50 p-3 md:grid-cols-[1fr_130px_80px_80px_80px_auto]"><input defaultValue={c.ten_cot} onBlur={e=>luuCot(c,{ten_cot:e.target.value})} className="h-10 rounded-lg border px-3"/><input type="number" defaultValue={c.do_rong} onBlur={e=>luuCot(c,{do_rong:Number(e.target.value)})} className="h-10 rounded-lg border px-3"/><label><input type="checkbox" defaultChecked={c.cho_tim_kiem} onChange={e=>luuCot(c,{cho_tim_kiem:e.target.checked})}/> Tìm</label><label><input type="checkbox" defaultChecked={c.hien_trong_danh_sach} onChange={e=>luuCot(c,{hien_trong_danh_sach:e.target.checked})}/> Bảng</label><label><input type="checkbox" defaultChecked={c.hien_trong_chi_tiet} onChange={e=>luuCot(c,{hien_trong_chi_tiet:e.target.checked})}/> Chi tiết</label><button onClick={()=>xoaCot(c)} className="font-bold text-red-600">Xóa</button></div>)}</div></div>}
{m==="vitri"&&<form onSubmit={luuViTri} className="mt-5 space-y-4"><label className="block font-bold">Tên hiển thị<input name="ten" defaultValue={d.catalog.tieu_de} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="block font-bold">Đề mục cấp 1<select name="dm" defaultValue={d.catalog.de_muc_id} className="mt-2 h-12 w-full rounded-xl border px-4">{dm.map(x=><option key={x.id} value={x.id}>{x.ten_de_muc}</option>)}</select></label><label className="block font-bold">Đề mục cấp 2<select name="dmc" defaultValue={d.catalog.de_muc_con_id||""} className="mt-2 h-12 w-full rounded-xl border px-4"><option value="">Hiển thị trực tiếp dưới cấp 1</option>{con.map((x:any)=><option key={x.id} value={x.id}>{x.ten_de_muc_con}</option>)}</select></label><button className="rounded-xl bg-blue-600 px-6 py-3 font-bold text-white">Lưu</button></form>}</div></div>}</main>}
